{"asctime": "2023-12-27T18:50:52Z", "levelname": "INFO", "name": "utils.log_utils", "module": "app_utils", "funcName": "read_data", "lineno": 24, "message": "data read successfully.."}
{"asctime": "2023-12-27T18:50:52Z", "levelname": "INFO", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 39, "message": "File processing successful!"}
{"asctime": "2023-12-27T18:51:04Z", "levelname": "ERROR", "name": "utils.log_utils", "module": "app_utils", "funcName": "read_data", "lineno": 31, "message": "Error reading file: [Errno 2] No such file or directory: '.data/input.txt'"}
{"asctime": "2023-12-27T18:51:04Z", "levelname": "ERROR", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 42, "message": "Custom Exception caught: fileReader::read_data(): FileNotFoundError - [Errno 2] No such file or directory: '.data/input.txt' [Line No 22]"}
{"asctime": "2023-12-27T18:52:03Z", "levelname": "INFO", "name": "utils.log_utils", "module": "app_utils", "funcName": "read_data", "lineno": 24, "message": "data read successfully.."}
{"asctime": "2023-12-27T18:52:03Z", "levelname": "INFO", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 39, "message": "File processing successful!"}
{"asctime": "2023-12-27T18:59:37Z", "levelname": "INFO", "name": "utils.log_utils", "module": "app_utils", "funcName": "read_data", "lineno": 24, "message": "data read successfully.."}
{"asctime": "2023-12-27T18:59:37Z", "levelname": "INFO", "name": "app.fileProcessor", "module": "fileProcessor", "funcName": "process_file", "lineno": 39, "message": "File processing successful!"}
